=== elwyne-mabanglo/n-tier-application/public_nginx/sowa/level1/dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT HolidayAccomodation (property*)>

<!ELEMENT property (price, location, address, bedroom, title, description,distance?, user, image* , addtionalDetails?)>

<!ATTLIST property propertyId CDATA #REQUIRED>

<!ATTLIST property db (BH|SW) "BH">

<!ELEMENT price (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT bedroom (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT distance (#PCDATA)>

<!ELEMENT user (username, email)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT image (imageType?,imageName?,imageData)>

<!ATTLIST image imageId CDATA #REQUIRED>

<!ELEMENT imageType (#PCDATA)>
<!ELEMENT imageName (#PCDATA)>
<!ELEMENT imageData (#PCDATA) >

<!ELEMENT addtionalDetails (kitchen?, bathroom?, livingRoom?, garage?, carpet?, latitude?, longitude?)>
<!ELEMENT kitchen (#PCDATA)>
<!ELEMENT bathroom (#PCDATA)>
<!ELEMENT livingRoom (#PCDATA)>
<!ELEMENT garage (#PCDATA)>
<!ELEMENT carpet (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>

=== elwyne-mabanglo/n-tier-application/public_nginx/sowa/level1/full.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HolidayAccomodation SYSTEM "U:\public_nginx\sowa\level1\dtd.dtd">
<HolidayAccomodation 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="U:\public_nginx\sowa\level1\xsd.xsd">
    <property propertyId="1" db="SW">
        <price>28000000</price>
        <location>Bracknell</location>
        <address>London Road, Bracknell, Berkshire RG12</address>
        <bedroom>1</bedroom>
        <title>Studio to rent</title>
        <description>
            A beautiful period house that has a contemporary style with oak floors and a modern kitchen along with very stylish bathrooms with limestone tiled floors and chrome fittings
        </description>
        <distance>1 0.27769431875377</distance>
        <user>
            <username>2</username>
            <email>me324@greenwich.ac.uk</email>
        </user>
        <image imageId="1">
            <imageType>image/jpeg</imageType>
            <imageName>1</imageName>
            <imageData>
                http://stu-nginx.cms.gre.ac.uk/~me324/sowa/pics/1.jpg
            </imageData>
        </image>
        <addtionalDetails>
            <kitchen>Yes</kitchen>
            <livingRoom>No</livingRoom>
            <garage>Yes</garage>
            <carpet>Yes</carpet>
            <latitude>51.4829</latitude>
            <longitude>-0.009592</longitude>
        </addtionalDetails>
    </property>
</HolidayAccomodation>

=== elwyne-mabanglo/n-tier-application/public_nginx/sowa/level1/blank.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HolidayAccomodation SYSTEM "U:\public_nginx\sowa\level1\dtd.dtd">
<HolidayAccomodation 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="U:\public_nginx\sowa\level1\xsd.xsd">
    <property propertyId="1" db="SW">
        <price>28000000</price>
        <location>Bracknell</location>
        <address>London Road, Bracknell, Berkshire RG12</address>
        <bedroom>1</bedroom>
        <title>Studio to rent</title>
        <description>
            A beautiful period house that has a contemporary style with oak floors and a modern kitchen along with very stylish bathrooms with limestone tiled floors and chrome fittings
        </description>
        <user>
            <username>2</username>
            <email>me324@greenwich.ac.uk</email>
        </user>
        <image imageId="1">
            <imageData>
                http://stu-nginx.cms.gre.ac.uk/~me324/sowa/pics/1.jpg
            </imageData>
        </image>
        <addtionalDetails>
            <kitchen>Yes</kitchen>
            <bathroom>Yes</bathroom>
            <livingRoom>Yes</livingRoom>
        </addtionalDetails>
    </property>
</HolidayAccomodation>
